### ISSUE TITLE
Documentation for pulling docker images from the cloud has a typo

### ISSUE THREAD

**Issue by razeh** [goldsborough/clang-expand#4]
The documentation for the pull says:
  docker pull goldsborough/clang-expand:latest-<os>

Which produces:
  [razeh@rdx-ws-001 rdx-code]$ docker pull goldsborough/clang-expand:latest-ubuntu 
  Pulling repository docker.io/goldsborough/clang-expand
  Tag latest-ubuntu not found in repository docker.io/goldsborough/clang-expand

When what you really want is:
  docker pull goldsborough/clang-expand:<os>-latest

Which produces:

[razeh@rdx-ws-001 rdx-code]$ docker pull goldsborough/clang-expand:latest-ubuntu
Pulling repository docker.io/goldsborough/clang-expand
Tag latest-ubuntu not found in repository docker.io/goldsborough/clang-expand
[razeh@rdx-ws-001 rdx-code]$ docker pull goldsborough/clang-expand:ubuntu-latest
ubuntu-latest: Pulling from goldsborough/clang-expand
8aec416115fd: Pull complete 
695f074e24e3: Pull complete 
946d6c48c2a7: Pull complete 
bc7277e579f0: Pull complete 
2508cbcde94b: Pull complete 
69c7dbb0d941: Pull complete 
f3f27fbd8dd9: Pull complete 
dd9334b7f001: Pull complete 
ab89bbc0b94b: Pull complete 
7e7740370bd7: Pull complete 
b181bc6e923d: Pull complete 
Digest: sha256:877f72dde527905783b13062ea3ece05394a2f56aa4aeba026d7b5329680641b
Status: Downloaded newer image for goldsborough/clang-expand:ubuntu-latest

**Comment by goldsborough** [comment]
Thanks, it should really be ubuntu-latest. I'll fix the image tag.

**Comment by goldsborough** [comment]
Fixed, thanks.
